//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DerectionSender
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestDerections
    {
        public System.Guid Id { get; set; }
        public System.Guid FK_Derections { get; set; }
        public string EmailBody { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.Guid FK_Contact { get; set; }
        public bool IsPost { get; set; }
        public Nullable<System.DateTime> PostedAt { get; set; }
        public bool IsDeleted { get; set; }
        public string Subject { get; set; }
    
        public virtual Contacts Contacts { get; set; }
        public virtual Derections Derections { get; set; }
    }
}
